COLUMN_SPACING = 5;
ROW_SPACING = 5;
		
MIN_WIDTH = 7;
MAX_WIDTH = 2;
		
//MAX_X_OFFSET = 10;
//MAX_Y_OFFSET = 10;
		
//ROTATION_MIN = 0;
//ROTATION_MAX = 360;
		
//ALPHA_MIN = 1;
//ALPHA_MAX = 1;