COLUMN_SPACING = 45;
ROW_SPACING = 45;
		
MIN_WIDTH = 100;
MAX_WIDTH = 50;
		
MAX_X_OFFSET = 30;
MAX_Y_OFFSET = 30;
		
ROTATION_MIN = 0;
ROTATION_MAX = 360;
		
//ALPHA_MIN = 1;
//ALPHA_MAX = 1;