COLUMN_SPACING = 30;
ROW_SPACING = 30;
		
MIN_WIDTH = 10;
MAX_WIDTH = 50;
		
//MAX_X_OFFSET = 10;
//MAX_Y_OFFSET = 10;
		
//ROTATION_MIN = 0;
//ROTATION_MAX = 360;
		
//ALPHA_MIN = 1;
//ALPHA_MAX = 1;