COLUMN_SPACING = 25;
ROW_SPACING = 25;
		
MIN_WIDTH = 30;
MAX_WIDTH = 30;
		
MAX_X_OFFSET = 0;
MAX_Y_OFFSET = 0;
		
ROTATION_MIN = 0;
ROTATION_MAX = 360;
		
//ALPHA_MIN = .5;
//ALPHA_MAX = 1;