COLUMN_SPACING = 35;
ROW_SPACING = 35;
		
MIN_WIDTH = 20;
MAX_WIDTH = 40;
		
MAX_X_OFFSET = 10;
MAX_Y_OFFSET = 10;
		
ROTATION_MIN = 0;
ROTATION_MAX = 360;
		
ALPHA_MIN = .5;
ALPHA_MAX = 1;